- hosts: all
  sudo: yes

  vars:
    datadir: /srv/fedora-atomic
    outputdir: /srv/fedora-atomic
    inboxdir: /srv/fedora-atomic/inbox
    releases:
      - name: f21
        gitbranch: f21
      - name: rawhide
        gitbranch: master

  tasks:
    - file: path={{ datadir }}/{{ item.name }}
            owner=root group=root mode=755 state=directory
      with_items: releases

    - git: repo=https://git.fedorahosted.org/git/fedora-atomic.git
           dest={{ datadir }}/{{ item.name }}/fedora-atomic
           version={{ item.gitbranch }}
           update=no
      with_items: releases

    - template: src=templates/atomic-compose.service.j2
                dest=/etc/systemd/system/atomic-compose-{{ item.name }}.service
                mode=0644
      with_items: releases

    - file: path={{ datadir }}/{{ item.name }}/repo src=../output/repo
            owner=root group=root state=link
      with_items: releases

    - file: path={{ datadir }}/{{ item.name }}/tasks/treecompose
            owner=root group=root mode=755 state=directory
      with_items: releases

    - name: Create initial treecompose
      action: copy content="" dest={{ inboxdir }}/treecompose
              owner=root group=rpmostreecompose mode=644

    - service: name=atomic-compose-{{ item.name }} enabled=yes state=started
      with_items: releases
      


